name: Deploy New Migrations To Supabase

on:
  push:
    branches: ['production']
    paths: ['supabase/migrations/**']

jobs:
  main:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_name == 'production' && github.ref_type == 'branch'

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASS }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: linking supabase project
        run: supabase link --project-ref $SUPABASE_PROJECT_ID -p $SUPABASE_DB_PASSWORD

      - name: migrations to be pushed
        run: supabase db push --dry-run --include-all

      - name: pushing changes to supabase
        run: supabase db push --include-all